"""Schémas publics de l'API."""

from hydro_api.schemas.core import (
    ApprovalResponse,
    CalculationCreate,
    CalculationRead,
    CalculationResultRead,
    CalculationSummaryRead,
    ModelVersionCreate,
    ModelVersionRead,
    OrganizationCreate,
    OrganizationRead,
    OrganizationUpdate,
    Page,
    ProjectCreate,
    ProjectRead,
    ProjectUpdate,
    ReportApproval,
    ReportCreate,
    ReportRead,
    ScenarioCreate,
    ScenarioRead,
    ScenarioUpdate,
)

__all__ = [
    "ApprovalResponse",
    "CalculationCreate",
    "CalculationRead",
    "CalculationResultRead",
    "CalculationSummaryRead",
    "ModelVersionCreate",
    "ModelVersionRead",
    "OrganizationCreate",
    "OrganizationRead",
    "OrganizationUpdate",
    "Page",
    "ProjectCreate",
    "ProjectRead",
    "ProjectUpdate",
    "ReportApproval",
    "ReportCreate",
    "ReportRead",
    "ScenarioCreate",
    "ScenarioRead",
    "ScenarioUpdate",
]
