"""Modèle métier pur de la plateforme.

Ce paquet ne dépend ni de FastAPI, ni de SQLAlchemy, ni du frontend (D11 § 4, règle de
dépendance). Il définit les objets typés que le noyau scientifique reçoit et les résultats
qu'il retourne, dans un système d'unités SI cohérent.
"""

from hydro_domain.canonical import CanonicalInput, Provenance
from hydro_domain.enums import (
    BoundaryKind,
    EdgeType,
    EquipmentStatus,
    FluidCategory,
    FrictionModel,
    NodeType,
    ObjectiveKind,
    PropertyQuality,
    PropertySource,
    PumpArrangement,
    PumpRole,
    TankType,
    TransferStopReason,
)
from hydro_domain.fluid import (
    REFERENCE_TEMPERATURE_K,
    STANDARD_PRESSURE_PA,
    Fluid,
    PropertyEvaluation,
    PropertyPoint,
    PropertyTable,
)
from hydro_domain.geometry import (
    TYPICAL_ROUGHNESS_M,
    ElevationProfile,
    Fitting,
    PipeSegment,
    ProfilePoint,
    validate_segment_chain,
)
from hydro_domain.interpolation import (
    ExtrapolationPolicy,
    InterpolationKind,
    MonotoneTable,
    TableEvaluation,
)
from hydro_domain.pipeline import InjectionPoint, Pipeline
from hydro_domain.pumps import (
    CurveEvaluation,
    G,
    PumpCurve,
    PumpInstance,
    PumpModel,
    QuadraticFit,
    absorbed_power_w,
    fit_quadratic_head,
    hydraulic_power_w,
)
from hydro_domain.results import (
    EnergySummary,
    GravityZone,
    ProfilePointResult,
    PumpResult,
    SegmentResult,
    SimulationResult,
    StationResult,
)
from hydro_domain.scenario import (
    BoundaryCondition,
    PumpOverride,
    Scenario,
    SegmentOverride,
    SolverOptions,
    StationOverride,
)
from hydro_domain.serialization import (
    canonical_input_from_dict,
    fluid_from_dict,
    pipeline_from_dict,
    pump_model_from_dict,
    pump_models_from_dict,
    scenario_from_dict,
    solver_options_from_dict,
)
from hydro_domain.stations import (
    PumpGroup,
    PumpStation,
    StationEvaluation,
    build_parallel_station,
    build_series_station,
    head_to_pressure_pa,
    pressure_to_head_m,
    velocity_head_m,
)
from hydro_domain.tanks import StrappingTable, Tank, TankLevels

__all__ = [
    "REFERENCE_TEMPERATURE_K",
    "STANDARD_PRESSURE_PA",
    "TYPICAL_ROUGHNESS_M",
    "BoundaryCondition",
    "BoundaryKind",
    "CanonicalInput",
    "CurveEvaluation",
    "EdgeType",
    "ElevationProfile",
    "EnergySummary",
    "EquipmentStatus",
    "ExtrapolationPolicy",
    "Fitting",
    "Fluid",
    "FluidCategory",
    "FrictionModel",
    "G",
    "GravityZone",
    "InjectionPoint",
    "InterpolationKind",
    "MonotoneTable",
    "NodeType",
    "ObjectiveKind",
    "PipeSegment",
    "Pipeline",
    "ProfilePoint",
    "ProfilePointResult",
    "PropertyEvaluation",
    "PropertyPoint",
    "PropertyQuality",
    "PropertySource",
    "PropertyTable",
    "Provenance",
    "PumpArrangement",
    "PumpCurve",
    "PumpGroup",
    "PumpInstance",
    "PumpModel",
    "PumpOverride",
    "PumpResult",
    "PumpRole",
    "PumpStation",
    "QuadraticFit",
    "Scenario",
    "SegmentOverride",
    "SegmentResult",
    "SimulationResult",
    "SolverOptions",
    "StationEvaluation",
    "StationOverride",
    "StationResult",
    "StrappingTable",
    "TableEvaluation",
    "Tank",
    "TankLevels",
    "TankType",
    "TransferStopReason",
    "absorbed_power_w",
    "build_parallel_station",
    "build_series_station",
    "canonical_input_from_dict",
    "fit_quadratic_head",
    "fluid_from_dict",
    "head_to_pressure_pa",
    "hydraulic_power_w",
    "pipeline_from_dict",
    "pressure_to_head_m",
    "pump_model_from_dict",
    "pump_models_from_dict",
    "scenario_from_dict",
    "solver_options_from_dict",
    "validate_segment_chain",
    "velocity_head_m",
]
