/** Jeu d'exemple minimal, conforme au schéma canonique hydro-input/1. */

export const EXAMPLE_MODEL: Record<string, unknown> = {
  units: {
    length: "m",
    elevation: "m",
    diameter: "m",
    roughness: "m",
    area: "m ** 2",
    volume: "m ** 3",
    mass: "kg",
    pressure: "Pa",
    head: "m",
    volumetric_flow: "m ** 3 / s",
    mass_flow: "kg / s",
    velocity: "m / s",
    density: "kg / m ** 3",
    dynamic_viscosity: "Pa * s",
    kinematic_viscosity: "m ** 2 / s",
    temperature: "K",
    power: "W",
    energy: "J",
    time: "s",
    rotational_speed: "1 / s",
    dimensionless: "dimensionless",
    currency_per_energy: "1 / J",
  },
  fluid: {
    id: "brut-leger",
    name: "Pétrole brut léger",
    category: "crude",
    reference_temperature_k: 288.15,
    reference_pressure_pa: 101325,
    density_kg_m3: 875,
    kinematic_viscosity_m2_s: 0.000009,
    vapor_pressure_pa: 10000,
    thermal_expansion_1_k: null,
    coolprop_name: null,
    density_table: null,
    kinematic_viscosity_table: null,
    vapor_pressure_table: null,
    data_source: "Données de démonstration",
    batch_reference: null,
  },
  network: {
    id: "PL-1",
    name: "Pipeline de démonstration",
    label: null,
    total_length_m: 50000,
    segments: [
      {
        id: "T1",
        sequence: 1,
        label: "Tronçon principal",
        length_m: 50000,
        inner_diameter_m: 0.5,
        outer_diameter_m: null,
        wall_thickness_m: null,
        roughness_m: 0.000045,
        material: null,
        maop_pa: 8000000,
        minimum_pressure_pa: null,
        start_chainage_m: 0,
        status: "available",
        fittings: [],
      },
    ],
    profile: {
      points: [
        { chainage_m: 0, elevation_m: 100, latitude: null, longitude: null },
        { chainage_m: 50000, elevation_m: 100, latitude: null, longitude: null },
      ],
    },
    stations: [],
    injections: [],
    origin_tank: null,
    destination_tank: null,
  },
  equipment: { pump_models: [] },
  rules: { rule_set_ids: [] },
};

export const EXAMPLE_SCENARIO: Record<string, unknown> = {
  temperature_k: null,
  imposed_flow_m3_s: 0.2,
  inlet_pressure_pa: 5000000,
  outlet_pressure_pa: null,
  inlet_tank_level_m: null,
  outlet_tank_level_m: null,
  pump_overrides: [],
  station_overrides: [],
  segment_overrides: [],
  solver: {
    friction_model: "colebrook_white",
    pressure_tolerance_pa: 1,
    mass_balance_tolerance: 0.000001,
    max_iterations: 100,
    profile_step_m: 1000,
    store_iterations: false,
    use_quadratic_pump_fit: false,
    max_flow_m3_s: null,
    detect_gravity_zones: true,
    apply_gravity_model: false,
    min_velocity_m_s: null,
    max_velocity_m_s: 3,
  },
  objective: null,
  energy_price_per_joule: null,
};

/** Charges utiles de départ pour les familles du catalogue technique. */
export const EXAMPLE_CATALOG_PAYLOADS: Record<string, Record<string, unknown>> = {
  fluids: EXAMPLE_MODEL.fluid as Record<string, unknown>,
  pumps: {
    manufacturer: "Constructeur à préciser",
    curve: {
      flows_m3_s: [0.1, 0.2, 0.3],
      heads_m: [210, 185, 145],
      efficiencies: [0.72, 0.82, 0.76],
      powers_w: null,
      npshr_m: [3.5, 4.5, 6.0],
      reference_speed_rpm: 3000,
      interpolation: "pchip",
    },
    motor_rated_power_w: 750000,
    npsh_margin_m: 1,
    min_speed_ratio: 0.7,
    max_speed_ratio: 1,
    minimum_continuous_flow_m3_s: 0.08,
    data_source: "Courbe constructeur à référencer",
  },
  valves: { k_coefficient: 0.2, nominal_diameter_m: 0.5 },
  materials: { roughness_m: 0.000045, mawp_pa: 8000000 },
  accessories: { k_coefficient: 0.3, accessory_type: "coude" },
};
